/**
 * @file    test_config.h
 * @brief   F7工程临时硬件测试的唯一选择开关。
 *
 * UART7复用测试、IC卡直连测试以及正式UART7业务不能同时拥有同一外设。
 * 因此工程只允许在本文件选择一个活动场景，默认为NONE。
 */

#ifndef TEST_CONFIG_H
#define TEST_CONFIG_H

#define LICANG_TEST_NONE                         0U
#define LICANG_TEST_MULT_UART_BAREMETAL          1U
#define LICANG_TEST_MULT_UART_FREERTOS           2U
#define LICANG_TEST_LSC16_BAREMETAL              3U
#define LICANG_TEST_LSC16_FREERTOS               4U
#define LICANG_TEST_IC_CARD_BAREMETAL            5U
#define LICANG_TEST_IC_CARD_FREERTOS             6U
#define LICANG_TEST_ZDT_TURNTABLE_BAREMETAL      7U
#define LICANG_TEST_ZDT_TURNTABLE_FREERTOS       8U
#define LICANG_TEST_MULT_UART_MODULES_FREERTOS    9U
#define LICANG_TEST_TURNTABLE_GRASP_LITE_FREERTOS 10U

/*
 * 实机测试时只修改下面这一行。
 * 正式代码交付和平时开发必须保持LICANG_TEST_NONE。
 */
#ifndef LICANG_ACTIVE_TEST
#define LICANG_ACTIVE_TEST                       LICANG_TEST_NONE
#endif

#if ((LICANG_ACTIVE_TEST != LICANG_TEST_NONE) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_MULT_UART_BAREMETAL) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_MULT_UART_FREERTOS) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_LSC16_BAREMETAL) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_LSC16_FREERTOS) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_IC_CARD_BAREMETAL) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_IC_CARD_FREERTOS) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_ZDT_TURNTABLE_BAREMETAL) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_ZDT_TURNTABLE_FREERTOS) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_MULT_UART_MODULES_FREERTOS) && \
     (LICANG_ACTIVE_TEST != LICANG_TEST_TURNTABLE_GRASP_LITE_FREERTOS))
#error "LICANG_ACTIVE_TEST is invalid"
#endif

#define MULT_UART_BAREMETAL_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_MULT_UART_BAREMETAL)

#define MULT_UART_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_MULT_UART_FREERTOS)

#define LSC16_BAREMETAL_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_LSC16_BAREMETAL)

#define LSC16_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_LSC16_FREERTOS)

#define IC_CARD_BAREMETAL_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_IC_CARD_BAREMETAL)

#define IC_CARD_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_IC_CARD_FREERTOS)

#define ZDT_TURNTABLE_BAREMETAL_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_ZDT_TURNTABLE_BAREMETAL)

#define ZDT_TURNTABLE_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_ZDT_TURNTABLE_FREERTOS)

#define MULT_UART_MODULES_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_MULT_UART_MODULES_FREERTOS)

#define TURNTABLE_GRASP_LITE_FREERTOS_TEST_ENABLED \
    (LICANG_ACTIVE_TEST == LICANG_TEST_TURNTABLE_GRASP_LITE_FREERTOS)

#endif /* TEST_CONFIG_H */
